apiVersion: apps/v1
kind: Deployment
metadata:
  name: AKS-migration-POC
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AKS-migration-POC
  template:
    metadata:
      labels:
        app: AKS-migration-POC
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: AKS-migration-POC
        image: aksmigrationstudy.azurecr.io/AKS-migration-POC:__Build.BuildId__
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: AKS-migration-POC
spec:
  ports:
  - port: 6379
  selector:
    app: AKS-migration-POC
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: AKS-migration-POC
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AKS-migration-POC
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: AKS-migration-POC
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: AKS-migration-POC
        image: aksmigrationstudy.azurecr.io/AKS-migration-POC:__Build.BuildId__
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "AKS-migration-POC"
